CREATE TABLE IF NOT EXISTS Employee (
ID_Employee VARCHAR(255) PRIMARY KEY NOT NULL,
Post VARCHAR(255) NULL,
FIO_Employee VARCHAR(255) NULL,
Login VARCHAR(255) NULL,
Password VARCHAR(255) NULL,
Last_Login VARCHAR(255) NULL,
Status_LogIn VARCHAR(255) NULL
);