CREATE TABLE IF NOT EXISTS Client (
FIO VARCHAR(255) NOT NULL,
ID_Client INT PRIMARY KEY auto_increment,
Passport VARCHAR(255) NOT NULL,
Datebirth VARCHAR(255) NOT NULL,
Address VARCHAR(255) NOT NULL,
Email VARCHAR(255) NOT NULL,
Password VARCHAR(255) NOT NULL
);